ok

diff --git a/utilmy/tools/mybash/mybash/folder b/utilmy/tools/mybash/mybash/folder
--- a/utilmy/tools/mybash/mybash/folder
+++ b/utilmy/tools/mybash/mybash/folder
@@ -1,38 +1,31 @@
 #!/bin/bash
-
-### Global vars ###################################
-
-## Acronyms:
-# spath 	: sorce path
-# dpath 	: destination path
-# maxc 		: maximum count
-# maxs		: maximum size
-# tfile		: topfile
-# rfile		: recentfile
-# csfile	: copysmallfile
-
-USAGE=$(cat << END
+USAGE=$(cat <<-END
      Perform various useful operations on the folders/directories
 
      folder
-     folder size	spath/								#### Print folder size in Gb			
-     folder tfile	spath/ 	20		"{excludedirs}"		#### Print 20 biggest size files		
-     folder rfile	spath/ 	10							#### Print recently modified files
-                                
-     folder backup	spath/	200m						#### copied into default path ~/zarchive/mypath_suffix_20230202/
-     folder backup	spath/	dpath/	200m				#### copied from mypathXYZ to mypath_target/
+     folder size        ./            #### Print folder size in Gb
+     folder topfile     ./   20       #### Print 20 biggest size files
+     folder recentifle  ./   10       #### Print recently modified files   
 
-     folder csfile	spath/	dpath/	-1000c				#### copy files recursively, filter big files
+                                
+     folder backup   mypathXYZ/                           #### copied into default path ~/zarchive/mypath_suffix_20230202/
+     folder backup   ~/mypathXYZ   ~/mypath_target/       #### copied from mypathXYZ to mypath_target/
+
+
+     folder copysmallfile   mypathFROm/   mypathTO/   100       ### copy files recursively, filter big files
+     
+
 END
 )
 
+#### Global Config. #################################
+# set -x  # Output commands being run.
+set -e  # Exit on error.
+
+
+#### Global vars ###################################
 FUNAME=`basename "$0"`
 YMD=$(date '+%Y%m%d')
-pathbase="backup_$YMD"
-dpath="~/zbackup/$pathbase"
-LIST=("size" "tfile" "rfile" "backup" "csfile")
-maxc=20
-maxs=200m
 
 
 #### Import utils #################################
@@ -41,76 +34,88 @@ source utils/util_stable.sh
 
 
 ### Input Params and Defaults ##################################
-[ $# -eq 0 ] && echo -e "$USAGE" && exit 0											###  No input, print doc
-[[ " ${LIST[*]} " =~ " $1 " ]] && task=$1 || task="size" 							###  Task, default: size
-[[ -d $2 ]] && spath=$2 || { echo -e "### This is PWD ###"; spath=$PWD; }			###  Path, default: current path
-[[ -d $3 ]] && dpath=$3 || [[ $3 == ?(-)+([0-9]) ]] && maxc=$3 || maxs=$3 			###  $3 : path, max count or max size
+[ $# -eq 0 ] &&    echo -e "$USAGE" && exit       ###  No input print doc
+task=$1    &&  [ -z $1 ] && task="size"           ###  print folder size
+ppath=$2   &&  [ -z $2 ] && ppath="$PWD"          ###  current path as default
 
-
-### Global Config. #################################
-# set -x  # Output commands being run.
-set -e  # Exit on error.
 
 ### Core ###########################################
+if [[ "$task" = size ]]; then
+      ssize=$3   &&  [ -z $3 ] &&  ssize=20 
 
-case $task in
-      ### Printing Information
-	"size")
-		df -H $spath
-    	      echo  # Newline
-		du -s -h $spath
-      ;;
+      df -h $ppath
+      echo  # Newline
+      du -h -d 10 $ppath     2>&1   |\
+         # grep '[0-9]G\>'         |\
+         grep -v 'denied'           |\ 
+         sort -hr                   |\
+         head -n $ssize 
 
-	"tfile")
-		[ ! -z $4 ] && eexcludedirs=$4 || eexcludedirs="0_BACKUP"
 
-    	df -H $spath
-    	echo  # Newline
-		
-		echo $temp
-
-    	while read -r str; do echo $str ; done < \
-			<( du -a $spath --exclude=$temp$eexcludedirs | sort -n -r | head -n $maxc | awk '{print $2}' )
-	;;
-	
-	
-	"rfile")
-		### recent file modified files + created
-		
-		if [[ "$OSTYPE" == "darwin"* ]]; then
-			### MacoS
-			while read -r str; do echo "$( date -r $str +'%F %T') $str " ; done < \
-				<( find $spath -type f -exec stat -lt "%F %T" {} \+ | cut -d' ' -f6- | sort -n | tail -n $maxc )
-			
-		else
-			while read -r str; do echo "$( date -r $str +'%F %T') $str " ; done < \
-				<( find $spath -type f -printf "%T %p\n" | sort -n | cut -d' ' -f2- | tail -n $maxc )
-		fi
-      ;;
-
-    	### Performing Operation
-	"backup")
-		### backup quickly currently folder, skip big files.
-
-		rsync -a --max-size=$maxs $spath $dpath
-	;;
-
-	"csfile")
-
-        ### Add File filtering
-        # echo "find $ppath -mindepth 1 -maxdepth 10 -type f -size $max_file_size -exec cp -t $dir_to"
-        cmd=$( find $spath -mindepth 1 -maxdepth 10 -type f -size $maxs -exec cp -t $dpath )
-
-        printf '%q ' "${cmd[@]}"
-        "${cmd[@]}"   ### Execute the command
-	;;
-
-	*)
-		echo -e "$USAGE"
-    ;;
-esac
 
 exit 0
+elif [[ "$task" = topfile ]]; then
+      ssize=$3          &&  [ -z $3 ] &&  ssize=20 
+      eexcludedirs=$4   &&  [ -z $4 ] &&  excludedirs="~/zzzzz" 
+
+      df -H $ppath
+      echo  # Newline
+      du -a $ppath  --exclude='${eexcludedirs}' |\
+         sort -n -r |\
+         head -n $ssize  
+
+
+
+exit 0
+elif [[ "$task" = recentfile ]]; then
+      ### recent file modified files + created
+      ssize=$3   &&  [ -z $3 ] &&  ssize=20 
+
+      if [[ "$OSTYPE" == "darwin"* ]]; then
+         ### MacoS
+         find $ppath -type f -exec stat -lt "%F %T" {} \+ | cut -d' ' -f6- | sort -n | tail -n $ssize
+      else 
+          ### Linux 
+          find $ppath -type f -printf "%T@ %p\n" | sort -n | cut -d' ' -f 2- | tail -n $ssize
+
+      fi
+
+
+exit 0
+elif [[ "$task" =  backup ]]; then
+      ### backup quickly currently folder, skip big files.
+      pathbase="backup_$YMD"
+      dir_to=$3  &&  [ -z $3 ]  &&  dir_to="~/zbackup/$pathbase"
+
+      rsync -ar $ppath  $dir_to
+
+
+
+
+exit 0
+elif [[ "$task" =  copysmallfile ]]; then
+      ### Copy only small files, exclude big one cplwf
+      pathbase="backup_$YMD"
+      dir_to=$3  &&  [ -z $3 ]  &&  dir_to="~/zbackup/$pathbase"
+      max_file_size="-$4c"  &&  [ -z $4 ] &&    max_file_size="-1000c"
+
+      #### Add File filtering
+      # echo "find $ppath -mindepth 1 -maxdepth 10 -type f -size $max_file_size -exec cp -t $dir_to"
+      cmd= (find $ppath -mindepth 1 -maxdepth 10 -type f -size $max_file_size -exec cp -t $dir_to )
+      
+      printf '%q ' "${cmd[@]}"
+      "${cmd[@]}"   ### Execute the command
+
+
+
+
+exit 0
+else
+   echo $USAGE
+fi
+
+
+
 
 
 
@@ -119,4 +124,3 @@ exit 0
 # printf 'Proposing to run: '
 # printf '%q ' "${cmd[@]}"
 # printf '\n'
-
