add: new alias file with some reformatting around the folder

diff --git a/utilmy/tools/mybash/mybash/nnetwork b/utilmy/tools/mybash/mybash/nnetwork
--- a/utilmy/tools/mybash/mybash/nnetwork
+++ b/utilmy/tools/mybash/mybash/nnetwork
@@ -1,21 +1,18 @@
 #!/bin/bash
-
 # set -x  # Output commands being run.
-set -e  # Exit on error.
+set -e # Exit on error.
 
-me=`basename "$0"`
-echo "######### ${me} #############################"
+USAGE="
+./$(basename $0) size | topfile | rename from to
+"
+
+echo " ######### $(basename "$0") #############################"
 NOW=$(date '+%Y%m%d')
 echo "$NOW"
 
 if [[ "$1" = listen ]]; then
    sudo lsof -i -P -n | grep LISTEN
-      
-
-      
-exit 0         
 else
-   1>&2 echo "Invalid arguments. Usage:
-
-./${me} size | topfile | rename from to"
+   echo -e "\nInvalid arguments. Usage:" 1>&2
+   echo ${USAGE}
 fi
